### PR TITLE
 V4.19.13

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [-] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
This version is incompatible with PyQt 5.6 and 5.9 (the first the default version in conda-forge, the last in defaults).

We could merge it but it won't make any difference in the stack because our PyQt is pinned to sip **4.18**. More importantly, we'll avoid the headache of people getting crashes in Spyder or other PyQt apps, after doing `conda update --all` (which seems to have become common these days).

So I'm -1 on this.

**Comment by mingwandroid** [comment]
@ccordoba12 do you have any tracking references to this incompatibility? Has a bug been filed anywhere?

I only ask because I looked at the rivercomputing site and didn't find anything.

**Comment by ccordoba12** [comment]
> do you have any tracking references to this incompatibility? Has a bug been filed anywhere?

Only this: https://github.com/AnacondaRecipes/pyqt-feedstock/pull/2

I discovered this problem when `defaults` updated `sip` to 4.19.12 and our test suite started to segfault at random places.

Besides, if you install the `pyqt5` pip package in a clean environment, you'll see that it pulls `sip` **4.19.8** and not higher versions.

**Comment by ccordoba12** [comment]
> if you install the pyqt5 pip package

I meant `pip install pyqt5==5.9.2`

**Comment by ccordoba12** [comment]
Closing this because it does't make sense for now (when Qt is updated to >5.9 then this will apply).

**Pull request closed without merging**
