### PR TITLE
Pypy38 pyheaptype

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Builds on #66 and adds a patch for PyPy

### CODE REVIEW

**Comment by mattip** [comment]
Windows is failing to apply the patch. The [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=679818&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=85) is
```
Applying patch: D:\a\1\s\recipe\patches/0001-pypy-no-ht_cached_keys with args:
['-Np1', '-i', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpur9mnd8r\\0001-pypy-no-ht_cached_keys.native', '--binary']
checking file sipbuild/module/source/13/sip_core.c
Hunk #1 FAILED at 245 (different line endings).
Hunk #2 FAILED at 9696 (different line endings).
```

Why would this happen? Both the files should be in unix fileformat.

Edit: the file did not have the proper suffix. Fixed in the subsequent commit.

**Comment by mattip** [comment]
CI, including PyPy3.8 and PyPy3.9, is passing. This is the top "IN-PR" package for the [pypy3.8 migration](https://conda-forge.org/status/#pypy38), it would nice to get it merged.

**Comment by mattip** [comment]
Thanks

**Comment by ocefpaf** [comment]
Thank you for fixing this!

**Pull request merged**
