### PR TITLE
Force rebuild using new conda-build

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Trying to unblock https://github.com/conda-forge/qgis-feedstock/pull/151

**Comment by ocefpaf** [comment]
Looks like the next conda-build will fix the prefix issue: https://github.com/conda/conda-build/pull/4126

(Thanks @isuruf for fixing it upstream!)

**Comment by SrNetoChan** [comment]
@ocefpaf so, what we do with this PR? Wait for the new build and restart?

**Comment by ocefpaf** [comment]
> @ocefpaf so, what we do with this PR? Wait for the new build and restart?

Yep :-)

I'll keep an eye on the new release and restart it here. It would be nice to add a test that fails in this situation to avoid regressions but that is not trivial.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by Tobias-Fischer** [comment]
Still pulls in the old conda-build (3.20.5) .. so no good to merge yet.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
It now picked up the new conda-build 3.21.0 and builds fine. I have no idea how to check whether the prefix was not properly replaced though ..

**Comment by ocefpaf** [comment]
> It now picked up the new conda-build 3.21.0 and builds fine. I have no idea how to check whether the prefix was not properly replaced though ..

@isuruf told me the offending files but I forgot :flushed: 
Isuru, do you mind taking a look? Also, due to the other problem you found with this release of conda-build, should we wait for another release?

**Comment by isuruf** [comment]
Looks good. `Lib/site-packages/sipconfig.py (text): Patching`
There was a new conda-build release today fixing the new release from yesterday

**Comment by SrNetoChan** [comment]
We need to have this fixed and merged before doing the PyQt build, right?

**Comment by ocefpaf** [comment]
> There was a new conda-build release today fixing the new release from yesterday

Let's wait for that one to re-kick the CIs here.

> We need to have this fixed and merged before doing the PyQt build, right?

In theory yest but I recall that @gillins was removing the `sip` dependency on `pyqt` to use the bundled one. I lost track of it though. TL;DR it won't hurt to wait but it may not be needed.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by Tobias-Fischer** [comment]
Looks like this is ready to go @conda-forge/sip

**Comment by gillins** [comment]
> I recall that @gillins was removing the sip dependency on pyqt to use the bundled one

Yeah turned out that `pyqt` needs a particular (older) `sip` to work (see https://github.com/conda-forge/pyqt-feedstock/pull/94#issuecomment-744478881) and bundles that version. So this `sip` recipe isn't much use with `pyqt` as it is too new.... I don't understand the details.

**Comment by ocefpaf** [comment]
Merging this is not needed for pyqt but still nice to have. Thanks @SrNetoChan, @Tobias-Fischer, and @gillins for all the work you did on this front!

**Pull request merged**
